SUPABASE_URL = "https://ydrypovzrfvmotlsaomw.supabase.co "  
SUPABASE_SERVICE_KEY = "sb_secret_xdljfyVFI8fcSFolTr3sMg_6Bc4yph3"  
BAILIAN_API_KEY = "sk-0be2a3a95c94481485486c88b55e94a9"  
DASHSCOPE_API_KEY = "sk-0be2a3a95c94481485486c88b55e94a9"  
