ZHIPU_API_KEY = "e1ac481e1b834f2482562f7143c392f2.9xhQNl3rfCy33tF8"  
SUPABASE_URL = "https://zgyzjxryvlgwzqkqfkoo.supabase.co "  
SUPABASE_SERVICE_KEY = "sb_secret_1Bi1unY-W2GkrzhDgKfqlw_M0GjMQXB"  
